# Generated by Django 4.1.7 on 2023-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(db_column='post_id', primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
    ]
